### ISSUE TITLE
cannot down load 

### ISSUE THREAD

**Issue by limelect** [newpascal/newpascal#3] opened 2016-10-25 06:05 UTC
cannot down load
https://github.com/newpascal/newpascal/releases/download/np_sc-v1.0.34/NPLazBaseWin32.rar
tried 4 times. with different  ways. FDM and more no success.

**Comment by LongDirtyAnimAlf** [comment] 2016-10-25 06:15
Strange. I just clicked the link you provided, and NPLazBaseWin32.rar downloads without problems.
So, I cannot reproduce.

**Comment by limelect** [comment] 2016-10-25 08:36
It stops in the middle of download. Try to download ALL !!!!
this is from FDM !!!
It stoped afte 94%

19:58:11 24/10/2016 Checking if download is malicious (see options to disable this)
19:58:12 24/10/2016 OK, FDM's users did not report that this download is malicious
19:58:12 24/10/2016 Starting download...
19:58:13 24/10/2016 Opening file on the disk...
19:58:13 24/10/2016 File already exists. Rename to "1942f9aa-986b-11e6-97fc-e880896e24f7(1).rar"
19:58:13 24/10/2016 Succeeded
19:58:13 24/10/2016 [Section 1] - Started
19:58:14 24/10/2016 [Section 1] - Downloading
19:58:16 24/10/2016 Preparing files on the disk... This may take several minutes
19:58:19 24/10/2016 Creating new section...
19:58:20 24/10/2016 [Section 2] - Started
19:58:20 24/10/2016 [Section 2] - Downloading
19:58:20 24/10/2016 Creating new section...
19:58:22 24/10/2016 [Section 3] - Started
19:58:22 24/10/2016 [Section 3] - Downloading
19:58:22 24/10/2016 Creating new section...
19:58:24 24/10/2016 [Section 4] - Started
19:58:24 24/10/2016 [Section 4] - Downloading
19:58:24 24/10/2016 Creating new section...
19:58:25 24/10/2016 [Section 5] - Started
19:58:26 24/10/2016 [Section 5] - Downloading
19:58:26 24/10/2016 Creating new section...
19:58:27 24/10/2016 [Section 6] - Started
19:58:28 24/10/2016 [Section 6] - Downloading
19:58:28 24/10/2016 Creating new section...
19:58:29 24/10/2016 [Section 7] - Started
19:58:30 24/10/2016 [Section 7] - Downloading
19:58:30 24/10/2016 Creating new section...
19:58:31 24/10/2016 [Section 8] - Started
19:58:32 24/10/2016 [Section 8] - Downloading
19:58:32 24/10/2016 Creating new section...
19:58:33 24/10/2016 [Section 9] - Started
19:58:34 24/10/2016 [Section 9] - Downloading
19:58:34 24/10/2016 Creating new section...
19:58:35 24/10/2016 [Section 10] - Started
19:58:35 24/10/2016 [Section 10] - Downloading
20:02:14 24/10/2016 [Section 5] - Done
20:02:14 24/10/2016 Creating new section...
20:02:16 24/10/2016 [Section 11] - Started
20:02:17 24/10/2016 [Section 11] - Downloading
20:03:23 24/10/2016 [Section 9] - Done
20:03:23 24/10/2016 Creating new section...
20:03:23 24/10/2016 [Section 10] - Server does not respond
20:03:23 24/10/2016 [Section 10] - Connecting...
20:03:25 24/10/2016 Access denied. Invalid user name or password
20:03:26 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:03:26 24/10/2016 [Section 10] - Pause 5 sec.
20:03:31 24/10/2016 [Section 10] - Connecting...
20:03:32 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:03:32 24/10/2016 [Section 10] - Pause 5 sec.
20:03:37 24/10/2016 [Section 10] - Connecting...
20:03:39 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:03:39 24/10/2016 [Section 10] - Pause 5 sec.
20:03:44 24/10/2016 [Section 10] - Connecting...
20:03:46 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:03:46 24/10/2016 [Section 10] - Pause 5 sec.
20:03:51 24/10/2016 [Section 10] - Connecting...
20:03:53 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:03:53 24/10/2016 [Section 10] - Pause 5 sec.
20:03:58 24/10/2016 [Section 10] - Connecting...
20:04:00 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:00 24/10/2016 [Section 10] - Pause 5 sec.
20:04:05 24/10/2016 [Section 10] - Connecting...
20:04:06 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:06 24/10/2016 [Section 10] - Pause 5 sec.
20:04:11 24/10/2016 [Section 10] - Connecting...
20:04:11 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:11 24/10/2016 [Section 10] - Pause 5 sec.
20:04:16 24/10/2016 [Section 10] - Connecting...
20:04:19 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:19 24/10/2016 [Section 10] - Pause 5 sec.
20:04:24 24/10/2016 [Section 10] - Connecting...
20:04:25 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:25 24/10/2016 [Section 10] - Pause 5 sec.
20:04:30 24/10/2016 [Section 10] - Connecting...
20:04:31 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:31 24/10/2016 [Section 10] - Pause 5 sec.
20:04:36 24/10/2016 [Section 10] - Connecting...
20:04:37 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:37 24/10/2016 [Section 10] - Pause 5 sec.
20:04:39 24/10/2016 [Section 1] - Done
20:04:42 24/10/2016 [Section 10] - Connecting...
20:04:43 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:43 24/10/2016 [Section 10] - Pause 5 sec.
20:04:48 24/10/2016 [Section 10] - Connecting...
20:04:49 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:49 24/10/2016 [Section 10] - Pause 5 sec.
20:04:54 24/10/2016 [Section 10] - Connecting...
20:04:55 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:04:55 24/10/2016 [Section 10] - Pause 5 sec.
20:05:00 24/10/2016 [Section 10] - Connecting...
20:05:01 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:05:01 24/10/2016 [Section 10] - Pause 5 sec.
20:05:06 24/10/2016 [Section 10] - Connecting...
20:05:08 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:05:08 24/10/2016 [Section 10] - Pause 5 sec.
20:05:13 24/10/2016 [Section 10] - Connecting...
20:05:13 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:05:13 24/10/2016 [Section 10] - Pause 5 sec.
20:05:18 24/10/2016 [Section 10] - Connecting...
20:05:19 24/10/2016 [Section 10] - Access denied. Invalid user name or password
20:05:19 24/10/2016 [Section 10] - Stopped
20:05:21 24/10/2016 [Section 8] - Done
20:06:10 24/10/2016 [Section 7] - Done
20:06:25 24/10/2016 [Section 11] - Done
20:06:32 24/10/2016 [Section 4] - Done
20:06:37 24/10/2016 [Section 3] - Done
20:06:38 24/10/2016 [Section 6] - Done
20:08:42 24/10/2016 [Section 2] - Server does not respond
20:08:42 24/10/2016 [Section 2] - Connecting...
20:08:42 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:08:42 24/10/2016 [Section 2] - Pause 5 sec.
20:08:47 24/10/2016 [Section 2] - Connecting...
20:08:48 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:08:48 24/10/2016 [Section 2] - Pause 5 sec.
20:08:53 24/10/2016 [Section 2] - Connecting...
20:08:54 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:08:54 24/10/2016 [Section 2] - Pause 5 sec.
20:08:59 24/10/2016 [Section 2] - Connecting...
20:08:59 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:08:59 24/10/2016 [Section 2] - Pause 5 sec.
20:09:04 24/10/2016 [Section 2] - Connecting...
20:09:05 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:05 24/10/2016 [Section 2] - Pause 5 sec.
20:09:10 24/10/2016 [Section 2] - Connecting...
20:09:11 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:11 24/10/2016 [Section 2] - Pause 5 sec.
20:09:16 24/10/2016 [Section 2] - Connecting...
20:09:16 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:16 24/10/2016 [Section 2] - Pause 5 sec.
20:09:21 24/10/2016 [Section 2] - Connecting...
20:09:22 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:22 24/10/2016 [Section 2] - Pause 5 sec.
20:09:27 24/10/2016 [Section 2] - Connecting...
20:09:28 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:28 24/10/2016 [Section 2] - Pause 5 sec.
20:09:33 24/10/2016 [Section 2] - Connecting...
20:09:34 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:34 24/10/2016 [Section 2] - Pause 5 sec.
20:09:39 24/10/2016 [Section 2] - Connecting...
20:09:39 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:39 24/10/2016 [Section 2] - Pause 5 sec.
20:09:44 24/10/2016 [Section 2] - Connecting...
20:09:45 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:45 24/10/2016 [Section 2] - Pause 5 sec.
20:09:50 24/10/2016 [Section 2] - Connecting...
20:09:51 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:51 24/10/2016 [Section 2] - Pause 5 sec.
20:09:56 24/10/2016 [Section 2] - Connecting...
20:09:56 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:09:56 24/10/2016 [Section 2] - Pause 5 sec.
20:10:01 24/10/2016 [Section 2] - Connecting...
20:10:02 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:10:02 24/10/2016 [Section 2] - Pause 5 sec.
20:10:07 24/10/2016 [Section 2] - Connecting...
20:10:08 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:10:08 24/10/2016 [Section 2] - Pause 5 sec.
20:10:13 24/10/2016 [Section 2] - Connecting...
20:10:13 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:10:13 24/10/2016 [Section 2] - Pause 5 sec.
20:10:18 24/10/2016 [Section 2] - Connecting...
20:10:19 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:10:19 24/10/2016 [Section 2] - Pause 5 sec.
20:10:24 24/10/2016 [Section 2] - Connecting...
20:10:25 24/10/2016 [Section 2] - Access denied. Invalid user name or password
20:10:25 24/10/2016 [Section 2] - Stopped
20:10:25 24/10/2016 Restarting download...
20:10:25 24/10/2016 Starting download...
20:10:26 24/10/2016 Access denied. Invalid user name or password
20:10:26 24/10/2016 Stopped
20:42:07 24/10/2016 Starting download...
20:42:08 24/10/2016 Access denied. Invalid user name or password
20:42:08 24/10/2016 Stopped
20:42:15 24/10/2016 Starting download...
20:42:16 24/10/2016 Access denied. Invalid user name or password
20:42:16 24/10/2016 Stopped
20:42:23 24/10/2016 Starting download...
20:42:24 24/10/2016 Access denied. Invalid user name or password
20:42:24 24/10/2016 Stopped
20:42:30 24/10/2016 Starting download...
20:42:31 24/10/2016 Access denied. Invalid user name or password
20:42:31 24/10/2016 Stopped
21:37:34 24/10/2016 Starting download...
21:37:36 24/10/2016 Access denied. Invalid user name or password
21:37:36 24/10/2016 Stopped
09:00:11 25/10/2016 Starting download...
09:00:12 25/10/2016 Access denied. Invalid user name or password
09:00:12 25/10/2016 Stopped
09:03:20 25/10/2016 Starting download...
09:03:21 25/10/2016 Access denied. Invalid user name or password
09:03:21 25/10/2016 Stopped

**Comment by BlumiMilch** [comment] 2016-10-25 11:08
Maybe it's not very helpful but I also had no problems downloading the file.
 I have no knowledge regarding any "Download Managers", in fact I have never used one, but your log seems suspicious to me. The file is publicly downloadable...  need to login anywhere, so why does it complain about username/password...

7zip reported the archive integrity of the rar file as "ok" and the sha256 of the file that I received is
f40ba52fbd0c889b192bf659dfa4288eb35a7c73dd0158e9458948cb73c313cb
You can use this value to check your file, in case you manage to get all the "parts"

**Comment by limelect** [comment] 2016-10-25 18:01
Finally i succeeded. A minute before that tried with FireFox always error. It did not even start.
Tried again with Chrom  normal download which NEVER succeeded this time OK.
So some thing is wrong. It took 3 days to download.

**Comment by LongDirtyAnimAlf** [comment] 2016-10-25 19:18
Thanks for the feedback !
Hope everything will work-out for you.
Closing now.

**Closed as completed by LongDirtyAnimAlf** 2016-10-25 19:18 UTC
